version: '3.9'

services:
  app:
    image: josephakayesi/cointracker
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - mongo
    depends_on:
      - mongo
    ports: 
      - '5000:5000'

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'